### ISSUE TITLE
High cpu usage when metrics stop coming , strange behavior after several hours of work 

### ISSUE THREAD

**Issue by vinnyvinny1989** [jlti-dev/ipsec_exporter#7] opened 2021-06-08 10:37 UTC
Hello, after start docker container, application worked fine for several hours. Then the following log was found in the docker container:

````
2021/05/27 10:04:49 Up and Running
2021/05/27 23:27:31 Error Connecting to vici: vici: transport error: dial unix /var/run/charon.vici: connect: resource temporarily unavailable
2021/05/27 23:28:02 Error Connecting to vici: vici: transport error: dial unix /var/run/charon.vici: connect: resource temporarily unavailable
2021/05/27 23:28:32 Error Connecting to vici: vici: transport error: dial unix /var/run/charon.vici: connect: resource temporarily unavailable
2021/05/27 23:29:01 Error Connecting to vici: vici: transport error: dial unix /var/run/charon.vici: connect: resource temporarily unavailable
````

And after this, i saw high cpu usage on the node. Prometheus metrics stopped working 
![image](https://i.ibb.co/q74qTbH/image-16.pngl)

I used **strongswan 5.8.2-1ubuntu3.1** installed on **Ubuntu 20.04.1 LTS (Focal Fossa)**

**Comment by LarsTi** [comment] 2021-06-08 15:00
Hi,
Is the socket still writable?
Can you check whats consuming your cpu with "top"?
The CPU consumption seemed to get up at the 28.05.21, your log entries are from late 27th, you have different time zones?

**Comment by LarsTi** [comment] 2021-06-15 08:03
Hey,
is there any update on this?

**Comment by vinnyvinny1989** [comment] 2021-06-15 12:06
> Hi,
> Is the socket still writable?
> Can you check whats consuming your cpu with "top"?
> The CPU consumption seemed to get up at the 28.05.21, your log entries are from late 27th, you have different time zones?

Time zones are the same, I'm not sure if these errors are somehow related to CPU consumption. But I would like to understand why they appear. The VPN worked fine at the same time.
I apologize, I could not see (using htop) what exactly loads the processor because it was a production environment, I had to quickly stop the service.

Have you ever experienced this behavior at work?

**Comment by LarsTi** [comment] 2021-06-15 12:17
No, i use this exporter for 3 Months and its running smoothly.
I highly doubt, that the cpu usage is related to the Error.
The cause is, the scrape is connecting to the vici socket. and THIS is already failing, so you should see the metric "number_of_ikes_connected" should be 0. every other metric should be empty.
The Scrape itself will (by default) timeout after 10 secs (afaik), this is a prometheus default.
So if you expect the exporter to cause the high usage, it should be 10 secs of high load, followed by 30 secs of low load (30 secs is your interval).

In case you experience those errors in the log, you should check the read/writability of the socket. You should check, if the `swanctl --list-sas` command is working.

It appears that your mount changed at runtime, but from here i cant tell you more.
If you need more help, we could check this via any kind of remote session (Teamviewer, AnyDesk).

**Comment by LarsTi** [comment] 2021-06-23 22:05
Hi, are there anymore updates? Or can we close the issue.
Did the problem occur again?

**Comment by vinnyvinny1989** [comment] 2021-06-24 10:30
Hello, I will try to repeat the situation in a test environment, after ths write the result. Pls don't close issue for now

**Comment by vinnyvinny1989** [comment] 2021-07-01 08:15
LarsTi, i'm reproduced the behavior

![image](https://i.ibb.co/5v3Sg8j/ipsec-exporter.png)

![image](https://i.ibb.co/bgNt8d8/ipsec-exporter-2.png)

When I enter the command "swanctl --list-sas", nothing happens next, waiting for output
Perhaps the problem how strongswan is configured, my swanctl conf file is

```
connections {
   aws-tunnel1 {
      local_addrs  = <ip address>
      remote_addrs = <ip address>

      local-1 {
         id = <ip address>
         auth = psk
      }

      remote-1 {
         id = <ip address>
         auth = psk
      }

      children {
         aws-tunnel1 {
            start_action = start
            updown = /usr/local/sbin/aws_updown.sh -ln ipsec0 -r <subnet>
            local_ts = 0.0.0.0/0
            remote_ts = 0.0.0.0/0
            life_time = 1h
            esp_proposals = aes128-sha1-modp1024
            dpd_action = start
         }
      }

      if_id_in = 42
      if_id_out = 42
      version = 2
      proposals = aes128-sha1-modp1024
      rekey_time = 8h
      reauth_time = 8h
      keyingtries = 0
      dpd_delay = 10s
      dpd_timeout = 30s
   }
}

secrets {
   ike-tunnel1 {
      id-local = <ip address>
      id-remote = <ip address>
      secret = <secret>
   }
}
```

**Comment by LarsTi** [comment] 2021-07-01 10:24
Hey,

i saw a lot of charon instances, i am not sure, if that is correct by the configuration, i dont use charon combined with systemd.
Your local and remote TS are the same? in that case, i dont know, if you should change that (as i only do tunneling one to many nets).
The problem seems also to occur, without the exporter, is that correct?
If so, you would probably need to open an issue at the official repo: https://github.com/strongswan/strongswan/issues
There should be no reason that swanctl is freezed at any time.

I am currently short of time, but can you provide both config files? seems like you are doing some road warrior scenario.
In case i find the time, i would try and help to look deeper in this.

**Comment by vinnyvinny1989** [comment] 2021-07-01 12:13
> The problem seems also to occur, without the exporter, is that correct?

No, if exporter not started, ipsec works fine. Now i try stop exporter container, after this CPU usage dropped to zero and commands like "swanctl --list-sas" started working normally.
Both config files are the same. 

If you have time, we could look at this together. Leave your contacts in some messenger please and we will agree more precisely

**Comment by LarsTi** [comment] 2021-07-06 08:40
Hey, sorry, i didn't find the time.
I will check this and contact you, as soon as i got a clue, whats happening.

Greetings,
LarsTi

**Comment by LarsTi** [comment] 2021-07-07 19:06
Hey,
I just released v0.5 (docker pull jlti-dev/ipsec_exporter:v0.5)
I fixed a bug, where each scrape opened the socket for read/write access, but never closed.

Could you please retry?
My prod System seems to have different thresholds, regarding the open sockets.

Kind regards,
LarsTi

**Comment by vinnyvinny1989** [comment] 2021-07-08 09:44
Ok, i deploy new version, and will write about the results in a couple of days. Thnx for your works

**Comment by vinnyvinny1989** [comment] 2021-07-09 08:00
launched container restarted themself, inside the following errors:

```
runtime stack:
runtime.throw(0x8c9bda, 0x16)
	/usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc004000000, 0x50000000, 0xbf8a70)
	/usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0xbdfb00, 0x4c800000, 0x42c177, 0xbdfb08)
	/usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0xbdfb00, 0x26263, 0x0)
	/usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0xbdfb00, 0x26263, 0x7ffcf8330100, 0x44095d)
	/usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x46a714)
	/usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1246

goroutine 8 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc000207520 sp=0xc000207518 pc=0x46a840
runtime.(*mheap).alloc(0xbdfb00, 0x26263, 0x101, 0x8)
	/usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc000207570 sp=0xc000207520 pc=0x427e25
runtime.(*mcache).allocLarge(0x7f35b683b108, 0x4c4c4544, 0x101, 0x0)
	/usr/local/go/src/runtime/mcache.go:224 +0x97 fp=0xc0002075c8 sp=0xc000207570 pc=0x418497
runtime.mallocgc(0x4c4c4544, 0x832ca0, 0x1, 0xc00046a7e4)
	/usr/local/go/src/runtime/malloc.go:1078 +0x925 fp=0xc000207650 sp=0xc0002075c8 pc=0x40dee5
runtime.makeslice(0x832ca0, 0x4c4c4544, 0x4c4c4544, 0x4)
	/usr/local/go/src/runtime/slice.go:98 +0x6c fp=0xc000207680 sp=0xc000207650 pc=0x44e6cc
github.com/strongswan/govici/vici.(*transport).recv(0xc00001e260, 0xc000207798, 0x0, 0x0)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/transport.go:96 +0x2d9 fp=0xc000207730 sp=0xc000207680 pc=0x7dfdd9
github.com/strongswan/govici/vici.(*Session).cmdTransportCommunicate(0xc0000560a0, 0xc000207798, 0x49ae8002077d8, 0xc0000c53e0, 0xc0000b5880)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/requests.go:132 +0x65 fp=0xc000207760 sp=0xc000207730 pc=0x7df065
github.com/strongswan/govici/vici.(*Session).streamEventRegisterUnregister(0xc0000560a0, 0x8c3ba4, 0x7, 0xc00008d700, 0x5, 0xc0000b5880)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/requests.go:107 +0x8e fp=0xc0002077e8 sp=0xc000207760 pc=0x7dee0e
github.com/strongswan/govici/vici.(*Session).handleStreamedRequest(0xc0000560a0, 0x8c415c, 0x8, 0x8c3ba4, 0x7, 0x0, 0x0, 0x946680, 0xc00008d7b0)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/requests.go:80 +0x4ea fp=0xc0002078c8 sp=0xc0002077e8 pc=0x7decea
github.com/strongswan/govici/vici.(*Session).sendStreamedRequest(0xc0000560a0, 0x8c415c, 0x8, 0x8c3ba4, 0x7, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/requests.go:61 +0x13d fp=0xc000207938 sp=0xc0002078c8 pc=0x7de77d
github.com/strongswan/govici/vici.(*Session).StreamedCommandRequest(...)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/session.go:216
main.listSAs(0x0, 0x0, 0x0, 0x0, 0x0)
	/app/main.go:26 +0x19f fp=0xc000207b40 sp=0xc000207938 pc=0x7fb11f
main.(*StrongswanCollector).Collect(0xc00015a000, 0xc000058180)
	/app/exporter.go:212 +0x37 fp=0xc000207f20 sp=0xc000207b40 pc=0x7f69f7
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x12b fp=0xc000207fe0 sp=0xc000207f20 pc=0x7d254b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000207fe8 sp=0xc000207fe0 pc=0x46c541
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x5ce

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f358fbb2e88, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00011c418, 0x72, 0x0, 0x0, 0x8c3acb)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00011c400, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:401 +0x212
net.(*netFD).accept(0xc00011c400, 0x55bfc794186e8c01, 0x0, 0x0)
	/usr/local/go/src/net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000a6dc8, 0x60e730cc, 0xc000099d80, 0x48ac26)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0000a6dc8, 0xc000099dd0, 0x18, 0xc000000180, 0x795c9b)
	/usr/local/go/src/net/tcpsock.go:261 +0x65
net/http.(*Server).Serve(0xc00015a0e0, 0x94c7f0, 0xc0000a6dc8, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2981 +0x285
net/http.(*Server).ListenAndServe(0xc00015a0e0, 0xc00015a0e0, 0x8)
	/usr/local/go/src/net/http/server.go:2910 +0xba
net/http.ListenAndServe(...)
	/usr/local/go/src/net/http/server.go:3164
main.main()
	/app/main.go:15 +0x154

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f358fbb2bd0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000068498, 0x72, 0x0, 0x4, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000068480, 0xc0000ad24c, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000068480, 0xc0000ad24c, 0x4, 0x4, 0x0, 0xc000032618, 0x44e6cc)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000ae278, 0xc0000ad24c, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
github.com/strongswan/govici/vici.(*transport).recv(0xc00001e280, 0xc031ea13586bc3df, 0x6459d1d73, 0xbc7fc0)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/transport.go:82 +0x8b
github.com/strongswan/govici/vici.(*eventListener).listen(0xc0000584e0)
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/events.go:132 +0x112
created by github.com/strongswan/govici/vici.newEventListener
	/go/pkg/mod/github.com/strongswan/govici@v0.5.1/vici/events.go:87 +0x151

goroutine 6 [select]:
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc0000808c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:513 +0xb65
github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x7f358fa0a0a8, 0xc0000720f0, 0xc00007e300)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/http.go:126 +0x99
net/http.HandlerFunc.ServeHTTP(0xc000150ee0, 0x7f358fa0a0a8, 0xc0000720f0, 0xc00007e300)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f358fa0a0a8, 0xc0000720f0, 0xc00007e300)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc000160030, 0x7f358fa0a0a8, 0xc0000720f0, 0xc00007e300)
	/usr/local/go/src/net/http/server.go:2069 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x94c9d0, 0xc000192000, 0xc00007e300)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/promhttp/instrument_server.go:101 +0xdf
net/http.HandlerFunc.ServeHTTP(0xc0001601b0, 0x94c9d0, 0xc000192000, 0xc00007e300)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0xbc7d80, 0x94c9d0, 0xc000192000, 0xc00007e300)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc00015a0e0, 0x94c9d0, 0xc000192000, 0xc00007e300)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00007a000, 0x94d5b8, 0xc00007c000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b

goroutine 7 [IO wait]:
internal/poll.runtime_pollWait(0x7f358fbb2da0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000068098, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000068080, 0xc000020131, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000068080, 0xc000020131, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e018, 0xc000020131, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xc000020120)
	/usr/local/go/src/net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	/usr/local/go/src/net/http/server.go:688 +0xd5

goroutine 9 [semacquire]:
sync.runtime_Semacquire(0xc000026058)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc000026050)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc000026050, 0xc000058180, 0xc0000581e0)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:463 +0x2b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:462 +0x60d
```

**Comment by LarsTi** [comment] 2021-07-12 20:38
Did this problem occure more than once?
It looks like the system is trying to allocate RAM, but i am not sure, why this should use that much RAM.
There seems to be a list, which is growing above the normal sizes.
How many connections are you monitoring? Still one?

**Comment by vinnyvinny1989** [comment] 2021-08-03 09:44
> 
> 
> Did this problem occure more than once?
> It looks like the system is trying to allocate RAM, but i am not sure, why this should use that much RAM.
> There seems to be a list, which is growing above the normal sizes.
> How many connections are you monitoring? Still one?

The error appears when the container is launched. After starting, a continuous restart begins. I'm trying to monitor two connections.

**Comment by LarsTi** [comment] 2022-04-23 18:54
Due to inactivity --> Closed

**Closed as completed by LarsTi** 2022-04-23 18:54 UTC
